### ISSUE TITLE
Только скрытые сообщения

### ISSUE THREAD

**Issue by Sperance** [JakeJMattson/DiscordKtExample#5]
Почему любые ответы от бота на команды - доступны только для текущего пользователя Дискорда? Как сделать чтобы ответ бота видели все на сервере?
![image](https://github.com/DiscordKt/ExampleBot/assets/43790253/bfcfd832-3eb6-43c2-9a84-77108d642f92)

**Comment by JakeJMattson** [comment]
> Why are any responses from the bot to commands only available to the current Discord user? How can I make the bot’s response visible to everyone on the server?

You can change `respond` to `respondPublic` and the response will be visible to everyone
```kotlin
slash(name = "Hello", description = "A 'Hello World' command") {
    execute { 
        respondPublic("Hello World!")
    }
}
```
![image](https://github.com/DiscordKt/ExampleBot/assets/22604455/db659b0b-d922-4d05-b404-816f42aa9104)

**Comment by Sperance** [comment]
Да, нашёл такую штуку, разобрался, спасибо большое
